WebApplication1/Controllers/BlogController.cs
using FisiovidaSystem.Lib.Entity;
using FisiovidaSystem.Lib.Service;
using FisiovidaSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FisiovidaSystem.Controllers
{
    public class BlogController : MasterController
    {
        // GET: Blog
        public ActionResult Index()
        {
            BlogModel model = new BlogModel();
            try
            {
                ConfiguracaoService configService = new ConfiguracaoService();
                model.Configuracao = configService.CarregarVariaveisContato();

                NovidadeService nService = new NovidadeService();
                model.Noticias = nService.Listar();
                model.TotalNoticias = nService.TotalRegistros;
            }
            catch (Exception e)
            {
                return RedirectToAction("InternalServer", "Erro");
            }
            return View(model);
        }
        public ActionResult Detalhe(int id)
        {
            NoticiaModel model = new NoticiaModel();
            try
            {
                ConfiguracaoService configService = new ConfiguracaoService();
                model.Configuracao = configService.CarregarVariaveisContato();


                NovidadeService nService = new NovidadeService();
                model.Noticia = nService.Carregar(id);
            }
            catch (Exception e)
            {
                return RedirectToAction("InternalServer", "Erro");
            }
            return View(model);
        }
        public ActionResult CarregaPagina(int pagina)
        {
            BlogModel model = new BlogModel();
            try
            {
                NovidadeService nService = new NovidadeService();
                model.Noticias = nService.Listar(pagina);
                model.TotalNoticias = nService.TotalRegistros;
            }
            catch (Exception e)
            {
                return RedirectToAction("InternalServer", "Erro");
            }
            return Json(new
            {
                sucesso = true,
                total = model.TotalNoticias,
                msg = RenderRazorViewToString("_NoticiasPartial", model)
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

WebApplication1/Controllers/ContatoController.cs
using FisiovidaSystem.Lib.Service;
using FisiovidaSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FisiovidaSystem.Controllers
{
    public class ContatoController : MasterController
    {
        // GET: Contato
        public ActionResult Index()
        {
            ContatoModel model = new ContatoModel();
            try
            {
                ConfiguracaoService configService = new ConfiguracaoService();
                model.Configuracao = configService.CarregarVariaveisContato();
            }
            catch (Exception ex)
            {
                return RedirectToAction("InternalServer", "Erro");
            }
            return View(model);
        }
    }
}

WebApplication1/Controllers/ModalidadeController.cs
using FisiovidaSystem.Lib.Entity;
using FisiovidaSystem.Lib.Model;
using FisiovidaSystem.Lib.Service;
using FisiovidaSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FisiovidaSystem.Controllers
{
    public class ModalidadeController : MasterController
    {
        // GET: Modalidade
        public ActionResult Index()
        {
            ModalidadesModel model = new ModalidadesModel();
            try
            {
                ModalidadeService service = new ModalidadeService();
                model.Modalidades = service.ListarModalidadesSite();

                ConfiguracaoService configService = new ConfiguracaoService();
                model.Configuracao = configService.CarregarVariaveisSite();
            }
            catch (Exception e)
            {

            }
            return View(model);
        }

        public ActionResult Detalhe(string modelID)
        {
            ModalidadeTratamentoModel model = new ModalidadeTratamentoModel();
            try
            {
                ConfiguracaoService configService = new ConfiguracaoService();
                model.Configuracao = configService.CarregarVariaveisSite();

                int tipo = Int32.Parse(modelID.Substring(0,1));
                int id = Int32.Parse(modelID.Substring(1));
                UsuarioService uService = new UsuarioService();
                if (tipo == 1) // modalidades
                {
                    ModalidadeService service = new ModalidadeService();
                    Modalidade t = service.Carregar(id);
                    model.ID = t.ID;
                    model.Nome = t.Nome;
                    model.VagasPorTurma = t.VagasPorTurma;
                    model.Duracao = t.Duracao;
                    model.Galeria = t.Galeria;
                    model.Descricao = t.Descricao;
                    model.Icones = t.Icones;
                    model.Professores = uService.ListaProfessoresModalidade(t.ID, 0);

                }
                else // tratamentos
                {
                    TratamentoService tService = new TratamentoService();
                    Tratamento t = tService.Carregar(id);
                    model.ID = t.ID;
                    model.Nome = t.Nome;
                    model.VagasPorTurma = 1;
                    model.Duracao = t.Duracao;
                    model.Galeria = t.Galeria;
                    model.Descricao = t.Descricao;
                    model.Icones = t.Icones;
                    model.Professores = uService.ListaProfessoresModalidade(0, t.ID);
                }

            }
            catch (Exception e)
            {

            }
            return View(model);
        }
    }
}

WebApplication1/Controllers/SobreController.cs
using FisiovidaSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FisiovidaSystem.Lib.Service;

namespace FisiovidaSystem.Controllers
{
    public class SobreController : MasterController
    {
        // GET: Sobre
        public ActionResult Index()
        {
            SobreModel model = new SobreModel();
            try
            {
                TagService service = new TagService();
                model.Diferenciais = service.ListarDiferenciais();

                ConfiguracaoService configService = new ConfiguracaoService();
                model.Configuracao = configService.CarregarVariaveisSite();

                UsuarioService uService = new UsuarioService();
                model.Professores = uService.ListarProfessores();
                model.TotalProfessores = model.Professores.Count;

                ModalidadeService mService = new ModalidadeService();
                model.TotalModalidades = mService.TotalModalidadesTratamentos();
            }
            catch (Exception ex)
            {

            }

            return View(model);
        }
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="~/Content/imagem/favicon.ico">

    <title>@ViewBag.Title</title>

    <!-- Bootstrap core CSS -->
    <link href="~/Content/css/bootstrap.css" rel="stylesheet">
    <link href="~/Content/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <link href="~/Content/css/carousel.css" rel="stylesheet">
    <link href="~/Content/css/m-carousel.css" rel="stylesheet">
    <link href="~/Content/css/minishare.css" rel="stylesheet">
    <link href="~/Content/css/custom.css" rel="stylesheet">
    <link href="~/Content/css/error.min.css" rel="stylesheet">


    <script src="~/Content/js/ie-emulation-modes-warning.js"></script>
    <script src="~/Content/js/ie-emulation-modes-warning.js"></script>
    @RenderSection("Scripts", false)
</head>
<body>

    <div class="navbar-wrapper no-pd">
        <div class="container">

            <nav class="navbar navbar-static-top">
                <div class="row">
                    <div class="navbar-header col-md-2 col-sm-2 row ">
                        <a class="f-right hidden-xs margem-logo" href="@Url.Action("Index", "Home")"><img src="~/Content/imagem/logo.png"></a>
                        <a class="f-right visible-xs hidden-sm hidden-md hidden-lg" class="logo-mobile" href="#"><img class="logo-mobile" src="~/Content/imagem/logo.png"></a>
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only"></span>
                            <span class="icon-bar"><img width="40" src="~/Content/imagem/i-menu.png"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <br class="clr">
                    </div>
                    <div id="navbar" class="navbar-collapse collapse menu-topo  col-md-7 col-sm-7">
                        <div class="menu-topo">
                            <ul class="nav navbar-nav">
                                <li><a class="@ViewBag.Home" href="@Url.Action("Index", "Home")">HOME</a></li>
                                <li><a class="@ViewBag.Sobre" href="@Url.Action("Index", "Sobre")">A MUDE</a></li>
                                <li><a class="@ViewBag.Modalidades" href="@Url.Action("Index","Modalidade")">MODALIDADES</a></li>
                                <li><a class="@ViewBag.Blog" href="@Url.Action("Index", "Blog")">BLOG</a></li>
                                <li><a class="@ViewBag.Contato" href="@Url.Action("Index","Contato")">CONTATO</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-3 hidden-xs f-right hidden">
                        <img class="f-left login hidden-sm" src="~/Content/imagem/login!.png">
                        <div class=" f-left largura">
                            <div class="form-group">
                                <div class="cols-sm-10">
                                    <div class="input-group">
                                        <span class="input-group-addon"><img src="~/Content/imagem/login_user.jpg" class="fa fa-users fa" aria-hidden="true"></span>
                                        <input type="text" class="form-control" name="username" id="username" placeholder="Usuário" />
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="cols-sm-10">
                                    <div class="input-group">
                                        <span class="input-group-addon"><img src="~/Content/imagem/login_senha.jpg" class="fa fa-lock fa-lg" aria-hidden="true"></span>
                                        <input type="password" class="form-control2" name="password" id="password" placeholder="Senha" />
                                        <button type="button" class="btn btn-primary btn-lg login-button pd-right">></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <br class="clr">
                    </div><br class="clr">
                </div>
            </nav>

        </div>
    </div>


    @RenderBody()



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../js/vendor/jquery.min.js"><\/script>')</script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="~/Content/js/vendor/holder.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="~/Content/js/ie10-viewport-bug-workaround.js"></script>
    <script src="~/Content/js/contagem.js"></script>
    <script src="~/Content/js/cascata.js"></script>

</body>
</html>